#!/bin/sh

export BITFLYER_API_KEY='YOUR_KEY'
export BITFLYER_API_SECRET='YOUR_SECRET'
export LINE_USERID='YOUR_USERID'
export LINE_CHANNEL_SECRET='YOUR_CHANNEL_SECRET'
export LINE_CHANNEL_TOKEN='YOUR_CHANNEL_TOKEN'

go run linebot_exec.go
